README.md
src/bot/deliver_job.rs
src/db/feeds.rs
src/db/telegram.rs
src/sync/feed_sync_job.rs
src/sync/sync_job.rs

Fixes https://github.com/ayrat555/el_monitorro/issues/5

Remove feeds that can not be processed

---

src/bot/deliver_job.rs

fixes https://github.com/ayrat555/el_monitorro/issues/23

fix western timezone offset

---

src/db/mod.rs

fixes https://github.com/ayrat555/el_monitorro/issues/30

truncate timestamps to seconds

---

src/bot/deliver_job.rs

fixes https://github.com/ayrat555/el_monitorro/issues/29

add additional telegram errors

---

src/bot/deliver_job.rs

resolves https://github.com/ayrat555/el_monitorro/issues/21

add the name of the feed to messages

---

src/bot/api.rs

Resolves https://github.com/ayrat555/el_monitorro/issues/13

start enabling the bot for channels

---

Cargo.lock
Cargo.toml
src/db.rs

fixes https://github.com/ayrat555/el_monitorro/issues/46

Add db connection pool

---

Cargo.lock
src/bin/cleaner.rs
src/bin/deliver.rs
src/bin/sync.rs
src/bot/api.rs
src/bot/deliver_job.rs
src/cleaner/clean_job.rs
src/db.rs
src/lib.rs
src/sync/feed_sync_job.rs
src/sync/sync_job.rs

fixes https://github.com/ayrat555/el_monitorro/issues/50

use semaphore to limit number of tasks

---

src/bot/deliver_job.rs

part of https://github.com/ayrat555/el_monitorro/issues/48

limit messages per second

---

README.md
src/bin/cleaner.rs
src/bin/deliver.rs
src/bin/sync.rs
src/bot/api.rs
src/bot/logic.rs

fixes https://github.com/ayrat555/el_monitorro/issues/57

configure periods and subscription limit

---

src/bot/deliver_job.rs
src/db/telegram.rs

fixes https://github.com/ayrat555/el_monitorro/issues/48
Instead of randomly selecting subscriptions, we will be fetching chats first and all subscriptions that belong to a chat.

process delivery by chats

---

src/bot/deliver_job.rs
src/db/telegram.rs

https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
```
Also note that your bot will not be able to send more than 20 messages per minute to the same group.
```

Process subscriptions per chats to not exceed telegram message limit

---

README.md
src/bot/api.rs

Resolves https://github.com/ayrat555/el_monitorro/issues/60

Add owner_telegram_id

---

src/bot/deliver_job.rs

fixes https://github.com/ayrat555/el_monitorro/issues/66

update last_delivered_at after every message

---

Cargo.lock
Cargo.toml

The master branch contains a bug -
https://github.com/telegram-rs/telegram-bot/issues/223
The fix wasn't merged -
https://github.com/telegram-rs/telegram-bot/pull/224

use custom for telegram-bot

---

src/sync/reader/atom.rs
tests/support/atom_feed_content.xml

fixes https://github.com/ayrat555/el_monitorro/issues/58

use `content` field if `summary` is not available

---

migrations/2020-12-26-102013_add_index_to_feed_items_created_at/down.sql
migrations/2020-12-26-102013_add_index_to_feed_items_created_at/up.sql
src/bot/deliver_job.rs
src/db/telegram.rs

fixes https://github.com/ayrat555/el_monitorro/issues/64

use created_at for delivery job

---

README.md
src/sync/reader.rs

fixes https://github.com/ayrat555/el_monitorro/issues/82

Make request timeout configurable

---

src/bot/deliver_job.rs

fixes https://github.com/ayrat555/el_monitorro/issues/84

fix `group was upgraded to supergroups`

---

src/sync/feed_sync_job.rs

fixes
```
Feb 28 16:00:40 vps695005 bash[9137]: thread 'sync-pool' panicked at 'called `Option::unwrap()` on a `None` value', src/sync/feed_sync_job.rs:35:20
Feb 28 16:00:40 vps695005 bash[9137]: stack backtrace:
Feb 28 16:00:40 vps695005 bash[9137]:    0: backtrace::backtrace::libunwind::trace
Feb 28 16:00:40 vps695005 bash[9137]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
Feb 28 16:00:40 vps695005 bash[9137]:    1: backtrace::backtrace::trace_unsynchronized
Feb 28 16:00:40 vps695005 bash[9137]:              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Feb 28 16:00:40 vps695005 bash[9137]:    2: std::sys_common::backtrace::_print_fmt
Feb 28 16:00:40 vps695005 bash[9137]: …
```

return error if feed is not found during sync

---

migrations/2021-03-07-131037_add_filter_words_to_subscriptions/down.sql
migrations/2021-03-07-131037_add_filter_words_to_subscriptions/up.sql
src/bot/api.rs
src/bot/deliver_job.rs
src/bot/logic.rs
src/db/telegram.rs
src/models/telegram_subscription.rs
src/schema.rs

Resolves https://github.com/ayrat555/el_monitorro/issues/45

Add subscription filters

---

Cargo.lock
Cargo.toml

I updated my fork of `telegram-bot` with fixes for new update types released today  https://core.telegram.org/bots/api-changelog#march-9-2021

add additional telegram lib fixes

---

README.md
src/bot/api.rs
src/bot/deliver_job.rs
src/bot/logic.rs

Resolves https://github.com/ayrat555/el_monitorro/issues/92

Negated filters

---

migrations/2021-08-21-091916_add_has_updates_to_subscription/down.sql
migrations/2021-08-21-091916_add_has_updates_to_subscription/up.sql
src/bot/deliver_job.rs
src/db/telegram.rs
src/models/telegram_subscription.rs
src/schema.rs
src/sync/feed_sync_job.rs

Deliver only subscriptions with new items

Optimize delivery

---

src/db/feeds.rs
src/db/telegram.rs

fix count queries

---

Cargo.lock
Cargo.toml
src/deliver/deliver_chat_updates_job.rs

fixes https://github.com/ayrat555/el_monitorro/issues/187

Change html parsing library

---

src/bot/commands.rs
src/bot/commands/remove_filter.rs
src/bot/commands/remove_global_template.rs
src/bot/commands/remove_template.rs
src/bot/commands/set_global_template.rs
src/bot/handler.rs
src/db/telegram.rs

resolves https://github.com/ayrat555/el_monitorro/issues/195

remove filter / template commands

---

Cargo.toml
src/bot/commands.rs
src/bot/commands/get_filter.rs
src/bot/commands/get_global_filter.rs
src/bot/commands/get_global_template.rs
src/bot/commands/get_template.rs
src/bot/commands/get_timezone.rs
src/bot/commands/help.rs
src/bot/commands/info.rs
src/bot/commands/list_subscriptions.rs
src/bot/commands/remove_filter.rs
src/bot/commands/remove_global_filter.rs
src/bot/commands/remove_global_template.rs
src/bot/commands/remove_template.rs
src/bot/commands/set_content_fields.rs
src/bot/commands/set_filter.rs
src/bot/commands/set_global_filter.rs
src/bot/commands/set_global_template.rs
src/bot/commands/set_template.rs
src/bot/commands/set_timezone.rs
src/bot/commands/start.rs
src/bot/commands/subscribe.rs
src/bot/commands/unknown_command.rs
src/bot/commands/unsubscribe.rs
src/bot/telegram_client.rs
src/deliver/render_message.rs

Reverts ayrat555/el_monitorro#241

Revert "Enable html in templates"

---

Cargo.lock
Cargo.toml

https://github.com/ayrat555/nanohtml2text/commit/600ebbe445074f298a4b694c3496d1c8bd2172b9
waiting to be released in the upstream repo

parse links along with their content

---

.github/workflows/rust.yml

Specify the postgres version when running tests

---

src/bot/commands.rs
src/bot/commands/start.rs

- add `commands` button to `/start` message
- disable `/commands` in groups and channels

CommandsKeyboard improvements

---

Cargo.lock
Cargo.toml

https://github.com/ayrat555/frankenstein/commit/357e83a76109df7f055220145775f1fdac44d2e8

update frankenstein (0.25.0)

---

.env
docker-compose.yml
src/main.rs

Docker compose updated to get easier the deployment.
This docker compose will :
- create the an instance of the bot with docker image from DockerHub
- create a PostgreSQL db , also pull from DockerHub

Docker compose 
